### PR TITLE
#345 - Refactor:  Clean folder structure

### PR DESCRIPTION
**Pull request by mukireus**
## Description
- Example projects have been moved to the `examples` folder.
- The used packages have been moved to the `packages` folder.

### See
| Before | After|
|--------|--------|
| Screenshot Before | Screenshot After | 

### Note
This change only includes `packages` and `examples`. In a new PR, we should also move the wolt_modal_sheet package into the packages folder.

## Related Issues
https://github.com/woltapp/wolt_modal_sheet/issues/345

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes tests for *all* changed/updated/fixed behaviors.
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] The package compiles with the minimum Flutter version stated in the [pubspec.yaml](https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8)

## Breaking Change
Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[Contributor Guide]: https://github.com/woltapp/wolt_modal_sheet/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ulusoyca — APPROVED** [review]

**Review by TahaTesser — CHANGES_REQUESTED** [review]
This looks good. However, in order to land this change we should also update examples references in the root [README](https://github.com/woltapp/wolt_modal_sheet/blob/main/README.md) file

**Comment by mukireus** [comment]
@TahaTesser Thank you for your review. I have updated the [README](https://github.com/woltapp/wolt_modal_sheet/blob/main/README.md) file.

**Comment by mukireus** [comment]
@ulusoyca Thank you for your review. 💙

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Pull request merged**
