### PR TITLE
[Demo App] Add widgetbook to coffee maker demo app

### PR DESCRIPTION
**Pull request by ulusoyca**
## Description

This PR only adds Widgetbook to demo app for education purposes on how to use Widgetbook

| Widgetbook Demo |
|--------|
| <video src="https://github.com/user-attachments/assets/2ee33a9f-c563-4d89-aa70-5c3fb9abc03a"> | 

## Related Issues

No related issue.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes tests for *all* changed/updated/fixed behaviors.
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] The package compiles with the minimum Flutter version stated in the [pubspec.yaml](https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8)

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[Contributor Guide]: https://github.com/woltapp/wolt_modal_sheet/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mukireus — APPROVED** [review]
Nth: If we're just going to build on the web, we don’t need the files for the other platforms. What are your thoughts on this?

**Comment by yousinix** [comment]
Hello @ulusoyca 👋 

Lucas told me you have some problems with the assets.
Here's how to quickly fix it:

1. Move assets from `coffee_maker_navigator_2/lib/assets` to `coffee_maker_navigator_2/assets`.
1. Add `pubspec.yaml` to `coffee_maker_navigator_2/assets` with the following content.

    ```yaml
    # coffee_maker_navigator_2/assets/pubspec.yaml
    name: assets
    description: >
      Holds the assets for the app. The assets are included in a
      separate package, to be able to share it with Widgetbook app.
    
    version: 0.0.0
    publish_to: none
    
    environment:
      sdk: ">=3.1.0 <4.0.0"
    
    flutter:
      assets:
        - images/
    ```
 
 1. Remove `assets` key from your app's `pubspec.yaml`:
 
     ```diff
     # coffee_maker_navigator_2/pubspec.yaml
     flutter:
      uses-material-design: true
    
     - assets:
     -   - assets/images/
     ```
 
1. Add `assets` dependency to your **app**'s `pubspec.yaml`:

    ```yaml
    # coffee_maker_navigator_2/pubspec.yaml
    dependencies:
      ...
      assets:
        path: assets
    ```
  
1. Add `assets` dependency to your **widgetbook**'s `pubspec.yaml`:

    ```yaml
    # coffee_maker_navigator_2/widgetbook/pubspec.yaml
    dependencies:
      ...
      assets:
        path: ../assets
    ```

1. Change all occurrences of `AssetImage` in your code as follows:
    
    ```dart
    // Before
    AssetImage('lib/assets/images/order_not_found.webp');
    
    // After
    AssetImage(
      'images/order_not_found.webp',
      package: 'assets',
    );
    ```

**Comment by yousinix** [comment]
I have also realized that your widgets look a bit unstyled, and that's because there was no `Theme` widget injected in your tree. That's why you need to use the [`MaterialThemeAddon`](https://docs.widgetbook.io/addons/theme-addon#material-theme-addon).

1. As the addon doesn't have access to the context when you pass the theme, you should remove the `context` parameter from your `

    ```dart
    # demo_ui_components/lib/src/theme_data/app_theme_data.dart
    class AppThemeData {
    
      static ThemeData themeData() {
        // This should be equal to Theme.of(context).textTheme
        // as it's using the default TextTheme. But this way
        // you don't need a context 
        final textTheme = ThemeData().textTheme;
    
        // ...
      }
    }
    ```
  
1. Then add this addon to Widgetbook as follows:

    ```dart
    # coffee_maker_navigator_2/widgetbook/lib/main.dart
    import 'package:demo_ui_components/demo_ui_components.dart';
    
    // ...
    
    @widgetbook.App()
    class WidgetbookApp extends StatelessWidget {
      const WidgetbookApp({super.key});
    
      @override
      Widget build(BuildContext context) {
        return Widgetbook.material(
          // ...
          addons: [
            // ...
            MaterialThemeAddon(
              themes: [
                WidgetbookTheme(
                  name: 'Default',
                  data: AppThemeData.themeData(),
                )
              ],
            )
          ],
        );
      }
    }
    ```
    
 ---
 
**Alternatively**, if you still think that the `context` is important to your theme, you can still use a custom [`ThemeAddon`](https://docs.widgetbook.io/addons/theme-addon#custom-theme-addon) as follows:

_(In my testing, both had same results, but the solution above is simpler IMO)_
 
```dart
ThemeAddon(
  themes: [
    const WidgetbookTheme(
      name: 'Default',
      data: AppThemeData.themeData,
    )
  ],
  themeBuilder: (context, themeBuilder, child) {
    return Theme(
      data: themeBuilder(context),
      child: child,
    );
  },
)
```

**Comment by ulusoyca** [comment]
Hi @yousinix  👋  Thank you for the detailed answer. Can you please check [this commit](2237e2561b8d6b6bc0f2c42a24f9b066fc7246e7)?

I still have error.

image

**Comment by ulusoyca** [comment]
> Hi @yousinix 👋 Thank you for the detailed answer. Can you please check [2237e25](https://github.com/woltapp/wolt_modal_sheet/commit/2237e2561b8d6b6bc0f2c42a24f9b066fc7246e7) ? I still have error.
> 
> image

Ok this worked! I just needed to remove the `assets/` from the path

const String _imagePath = 'images/coffee_maker_state';

**Pull request merged**
