### PR TITLE
Switch flutter_keyboard_visibility with flutter native check

### PR DESCRIPTION
**Pull request by moshe5745**
## Description

Deleting the flutter_keyboard_visibility package and replacing it with native flutter logic.

## Related Issues

(https://github.com/woltapp/wolt_modal_sheet/issues/210)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

Failing tests - Dont have time to figure out whats going on. Maybe someone will help me.

## Breaking Change

No

[Contributor Guide]: https://github.com/woltapp/wolt_modal_sheet/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by ulusoyca** [comment]
Thanks @moshe5745 It looks like your solution works and it is super exciting!

However I see a delay with the top bar visibility adjustment as I recorded in this video. Do you have time to check this? I will also check when I have time.

https://github.com/user-attachments/assets/71b7672c-dcab-4cd5-81bf-996164b7496d

**Comment by moshe5745** [comment]
I will check it
Maybe the debounce is not the right approach here, and throttle is the right one.

**Comment by ulusoyca** [comment]
> I will check it Maybe the debounce is not the right approach here, and throttle is the right one.

Great. you can test with the playground app

**Comment by ulusoyca** [comment]
@moshe5745 Can you check my PR: https://github.com/woltapp/wolt_modal_sheet/pull/303

I came up with more modular solution inspired from this PR.

**Pull request closed without merging**
